### ISSUE TITLE
Stack-trace appears if the image baseline not exists on AWS

### ISSUE THREAD

**Issue by lukasr22** [newsuk/AyeSpy#90]
If the image baseline not exists on AWS the stack trace appears instead of nice formatted error.

Scenario: try to compare the images which not exists on S3 bucket AWS and the AyeSpy returns error.

```
info [comparisonActions] : Getting baseline images from S3...

.../node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

TypeError: Cannot read property 'Body' of null
    at Response.s3.getObject (.../node_modules/aye-spy/lib/remoteActions.js:134:47)
    at Request.<anonymous> (.../node_modules/aws-sdk/lib/request.js:364:18)
    at Request.callListeners (/Users/lukas/Work/News_1/nu-sun-titan/node_modules/aws-sdk/lib/sequential_executor.js:109:20)
    at Request.emit (.../node_modules/aws-sdk/lib/sequential_executor.js:81:10)
    at Request.emit (.../node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (.../node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (.../node_modules/aws-sdk/lib/state_machine.js:14:12)
    at .../node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (.../node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (.../node_modules/aws-sdk/lib/request.js:685:12)
```

**Comment by L0wry** [comment]
#129
